version: "3.3"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    network_mode: host
    ports:
      # - "8080:80"
      # - "442:443"
      # - "8081:8081"  # For Traefik dashboard
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "./traefik/dynamic_config.yml:/etc/traefik/dynamic_config.yml:ro"
      - "./letsencrypt/cert:/etc/traefik/acme"
    restart: unless-stopped
