tls:
  options:
    modern:
      minVersion: VersionTLS12
      curvePreferences:
        - CurveP521
        - CurveP384

http:
  routers:
    # http-to-https:
    #   rule: "HostRegexp(`{host:.+}`)"
    #   entryPoints:
    #     - web
    #   middlewares:
    #     - redirect-to-https
    #   service: noop

    # www-to-non-www:
    #   rule: "Host(`www.orca.falktron.dev`)"
    #   entryPoints:
    #     - websecure
    #   middlewares:
    #     - redirect-to-non-www
    #   service: noop

    bitrix-router:
      rule: "Host(`t99ltd.info`)"
      entryPoints:
        - websecure
      middlewares:
        - auth
      service: bitrix
      tls:
        certResolver: letsencrypt
        options: modern
    # api:
    #   rule: Host(`traefik.DOMAIN.net`)
    #   entrypoints:
    #     - websecure
    #   middlewares:
    #     - Auth
    #   service: api@internal
    #   tls:
    #     certResolver: letsencrypt
    #     options: modern

    traefik-dashboard:
      rule: "Host(`traefik.t99ltd.info`)"
      # entryPoints:
      #   - websecure
      service: traefik
      tls:
        certResolver: letsencrypt
        options: modern
      middlewares:
        - auth

  middlewares:
    # redirect-to-https:
    #   redirectScheme:
    #     scheme: https
    #     permanent: true

    # redirect-to-non-www:
    #   redirectRegex:
    #     regex: "^https://www\\.(.*)"
    #     replacement: "https://$1"
    #     permanent: true
    
    auth:
      basicAuth:
        users:
          - "admin:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"  # admin/admin (example)
  services:
    traefik:
      loadBalancer:
        servers:
          - url: http://localhost:8080/
    bitrix:
      loadBalancer:
        servers:
          - url: "http://localhost:80"

    # noop:
    #   loadBalancer:
    #     servers:
    #       - url: "http://localhost"
