http:
  routers:
    # http-to-https:
    #   rule: "HostRegexp(`{host:.+}`)"
    #   entryPoints:
    #     - web
    #   middlewares:
    #     - redirect-to-https
    #   service: noop

    # www-to-non-www:
    #   rule: "Host(`www.orca.falktron.dev`)"
    #   entryPoints:
    #     - websecure
    #   middlewares:
    #     - redirect-to-non-www
    #   service: noop

    bitrix-router:
      rule: "Host(`orca.falktron.dev`)"
      entryPoints:
        - websecure
      middlewares:
        - auth
      tls:
        certResolver: letsencrypt
      service: bitrix
    
    traefik-dashboard:
      rule: "Host(`proxy.orca.falktron.dev`)"
      entryPoints:
        - traefik
      service: api@internal
      middlewares:
        - auth

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    redirect-to-non-www:
      redirectRegex:
        regex: "^https://www\\.(.*)"
        replacement: "https://$1"
        permanent: true
    
    auth:
      basicAuth:
        users:
          - "admin:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"  # admin/admin (example)

  services:
    bitrix:
      loadBalancer:
        servers:
          - url: "http://localhost:80"

    noop:
      loadBalancer:
        servers:
          - url: "http://localhost"
