entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8081"

api:
  dashboard: true

providers:
  file:
    filename: "/etc/traefik/config.yml"
    watch: true

log:
  level: DEBUG

accessLog: {}

certificatesResolvers:
  letsencrypt:
    acme:
      email: m.mut@falktron.de
      storage: /etc/traefik/acme/acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      tlsChallenge: {}
      # httpChallenge:
      #   entryPoint: web
