entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true

providers:
  file:
    filename: "/etc/traefik/config.yml"
    watch: true

log:
  level: DEBUG

accessLog: {}

# Enable the Traefik dashboard and API
entryPoints:
  traefik:
    address: ":8081"

http:
  routers:
    traefik:
      rule: "Host(`proxy.orca.falktron.dev`)"
      service: api@internal
      entryPoints:
        - "traefik"
      middlewares:
        - auth

  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"  # admin/admin (example)

certificatesResolvers:
  letsencrypt:
    acme:
      email: m.mut@falktron.de
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web
